In [10]:
import pandas as pd 
from matplotlib import pyplot as plt 
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

df = pd.read_csv('salaries.csv')
df.head()

   Years of Experience  Education Level  Age  Location Factor  Salary
0                   29                1   49                7  124204
1                   27                3   45                4  125948
2                   20                4   41                8  116078
3                   14                4   37                5  106486
4                   20                3   42                7  113297

In [11]:
df.shape

(1000, 5)

In [12]:
x = df.drop('Salary', axis = 'columns')
y = df['Salary']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=10)

model_full = LinearRegression()
model_full.fit(x_train,y_train)
model_full.score(x_test,y_test)

0.9525773624816919

In [13]:
model_full.intercept_

np.float64(52608.487605282404)

In [14]:
model_full.coef_

array([2113.98280589, 5007.82035443, -123.21488799, 1487.64526717])

In [15]:
y_test[:1]

841    151272
Name: Salary, dtype: int64

In [16]:
x_test[:1]

     Years of Experience  Education Level  Age  Location Factor
841                   38                1   56                9

In [17]:
model_full.predict(x_test[:1])

array([144436.42826039])